name: Create Draft Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: ${{ secrets.HYPERSWITCH_SENTRY_DSN }}
      SENTRY_ENV: 'production'
      HYPERSWITCH_PRODUCTION_URL: ${{ secrets.HYPERSWITCH_PRODUCTION_URL }}
      HYPERSWITCH_INTEG_URL: ${{ secrets.HYPERSWITCH_INTEG_URL }}
      HYPERSWITCH_SANDBOX_URL: ${{ secrets.HYPERSWITCH_SANDBOX_URL }}
      HYPERSWITCH_LOGS_PATH: ${{ secrets.HYPERSWITCH_LOGS_PATH }}
      PROD_ASSETS_END_POINT: ${{ secrets.PROD_ASSETS_END_POINT }}
      SANDBOX_ASSETS_END_POINT: ${{ secrets.SANDBOX_ASSETS_END_POINT }}
      INTEG_ASSETS_END_POINT: ${{ secrets.INTEG_ASSETS_END_POINT }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTORELEASE_PAT || github.token }}

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Capture Initial Version
        run: echo "INITIAL_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Run Semantic Release
        run: npx semantic-release

      - name: Check if Version Changed
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          echo "VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          if [ "${{ env.INITIAL_VERSION }}" = "$CURRENT_VERSION" ]; then
            echo "RELEASE_PERFORMED=false" >> $GITHUB_ENV
            echo "No new version was released"
          else
            echo "RELEASE_PERFORMED=true" >> $GITHUB_ENV
            echo "New version $CURRENT_VERSION was released"
          fi

      - name: Checkout Android Repository
        if: env.RELEASE_PERFORMED == 'true'
        uses: actions/checkout@v4
        with:
          repository: manideepk90/hyperswitch-sdk-android
          ref: main
          path: android
          token: ${{ secrets.AUTORELEASE_PAT || github.token }}

      - name: Checkout IOS Repo
        if: env.RELEASE_PERFORMED == 'true'

        uses: actions/checkout@v4
        with:
          repository: manideepk90/hyperswitch-sdk-ios
          ref: main
          path: ios
          token: ${{ secrets.AUTORELEASE_PAT || github.token }}

      - name: Checkout Shared Code Repo
        if: env.RELEASE_PERFORMED == 'true'
        uses: actions/checkout@v4
        with:
          repository: juspay/hyperswitch-sdk-utils
          ref: main
          path: shared-code

      - name: build bundles
        if: env.RELEASE_PERFORMED == 'true'
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          # Build bundles in parallel
          yarn re:build
          yarn bundle:android &
          yarn bundle:ios &
          wait
          
          # Commit Android bundle
          cd android
          git add ./app/src/main/assets/hyperswitch.bundle
          if ! git diff --staged --quiet; then
            git commit -m "chore(release): v${{ env.VERSION }} Android Bundle update [skip ci]"
            git push origin main
          fi
          cd ..
          
          # Commit iOS bundle
          cd ios
          git add ./hyperswitchSDK/Core/Resources/hyperswitch.bundle
          if ! git diff --staged --quiet; then
            git commit -m "chore(release): v${{ env.VERSION }} IOS Bundle update [skip ci]"
            git push origin main
          fi
